"""
MAKU AI Advisor Layer
=====================
Takes the transparent risk_engine.py outputs and produces:
  1. A rule-based hierarchy-of-controls recommendation (always works, no API needed)
  2. An optional plain-language narrative generated by the Anthropic API,
     if the user supplies an API key. This keeps the app fully functional
     offline/without a key, while demonstrating a genuine "AI reasoning"
     layer when a key is present - useful for the capstone demo.

Safety culture principle (informs the narrative below): compliance is the
OUTPUT of an authentic safety culture, not administrative theater - a
control list checked off on paper means nothing if it wasn't actually
implemented on site. The real test of that culture is what leadership
chooses in the moment a genuine risk-vs-cost tradeoff appears: whether they
control the risk, or cut the cost. Every AI briefing this module generates
is written to reflect that distinction, not just to restate the numbers.
"""

from __future__ import annotations

import asyncio
import os
import queue
import threading

import requests
import streamlit as st

from regulatory_references import get_references, get_further_reading

def _resolve_ai_config() -> dict:
    """
    CONFIGURATION EXTERNALIZATION (Phase 2.2): the model identifier, API
    base URL, and web-search max_uses parameter used to be plain hardcoded
    module constants. They are now resolved from configuration external to
    this source file - same secrets-then-env-then-default resolution order
    auth.py already uses for credentials (see that module's docstring) -
    so an operator can point this app at a new model string, a different
    API endpoint (e.g. an enterprise API gateway in front of Anthropic's
    API), or a different web-search budget without editing source code and
    redeploying.

    Resolution order per value:
      1. st.secrets["ai"]["model"] / ["api_base_url"] / ["web_search_max_uses"]
         / ["api_key"] - see .streamlit/secrets.toml.example for the exact
         TOML shape.
      2. MAKU_AI_MODEL / MAKU_AI_API_BASE_URL / MAKU_AI_WEB_SEARCH_MAX_USES
         / MAKU_AI_API_KEY environment variables.
      3. The hardcoded defaults below, which match this file's original
         values exactly - an unconfigured deployment behaves identically to
         before this refactor. This is purely additive externalization, not
         a behavior change. api_key has no default - None means "no
         server-side key configured", which is a valid, supported state
         (see get_configured_ai_api_key()'s docstring).

    Every lookup is individually wrapped in try/except so a missing
    secrets.toml, a missing [ai] table, or a malformed value can never
    raise - it just falls through to the next source, exactly like
    auth._configured_users() does for credentials.

    P0 "AUTHENTICATION & CRYPTOGRAPHIC HARDENING" - CONFIG EXTERNALIZATION:
    api_key resolution is what lets app.py's sidebar stop requiring every
    individual operator to paste in their own personal Anthropic API key
    (a "local user API key constraint") - once a server-side key is
    configured here, the whole deployment shares one centrally-managed,
    st.secrets-held credential instead. See
    get_configured_ai_api_key()/render_ai_layer_sidebar-equivalent in
    app.py's _render_ai_layer_sidebar().
    """
    try:
        model = str(st.secrets["ai"]["model"]).strip() or None
    except Exception:  # noqa: BLE001 - no secrets.toml / no [ai] table / no "model" key
        model = None
    try:
        api_base_url = str(st.secrets["ai"]["api_base_url"]).strip() or None
    except Exception:  # noqa: BLE001
        api_base_url = None
    try:
        web_search_max_uses = int(st.secrets["ai"]["web_search_max_uses"])
    except Exception:  # noqa: BLE001
        web_search_max_uses = None
    try:
        api_key = str(st.secrets["ai"]["api_key"]).strip() or None
    except Exception:  # noqa: BLE001
        api_key = None

    model = model or os.environ.get("MAKU_AI_MODEL", "").strip() or "claude-sonnet-4-5"
    api_base_url = (
        api_base_url
        or os.environ.get("MAKU_AI_API_BASE_URL", "").strip()
        or "https://api.anthropic.com/v1/messages"
    )
    if web_search_max_uses is None:
        env_max_uses = os.environ.get("MAKU_AI_WEB_SEARCH_MAX_USES", "").strip()
        web_search_max_uses = int(env_max_uses) if env_max_uses.isdigit() else 3
    api_key = api_key or os.environ.get("MAKU_AI_API_KEY", "").strip() or None

    return {"model": model, "api_base_url": api_base_url, "web_search_max_uses": web_search_max_uses,
            "api_key": api_key}


_AI_CONFIG = _resolve_ai_config()
ANTHROPIC_URL = _AI_CONFIG["api_base_url"]
MODEL = _AI_CONFIG["model"]
WEB_SEARCH_MAX_USES = _AI_CONFIG["web_search_max_uses"]


def get_configured_ai_api_key() -> str | None:
    """Returns the server-side Anthropic API key resolved from st.secrets/
    the environment at import time, or None if no server-side key is
    configured. app.py's sidebar calls this FIRST and only falls back to
    a per-operator manual text-input box when this returns None - see
    _render_ai_layer_sidebar() in app.py. Re-reads _AI_CONFIG rather than
    caching separately so a test that monkeypatches _AI_CONFIG directly
    is respected."""
    return _AI_CONFIG.get("api_key")

# Every existing function in this file talks to the Anthropic API with
# plain `requests` (zero extra SDK dependency - a deliberate original
# design choice). The `anthropic` Python SDK is used ONLY for the two new
# performance-layer additions below (token streaming via the sync
# Anthropic client, and the background-thread job via AsyncAnthropic) -
# it is an additive, optional dependency: every existing function keeps
# working unchanged even if it isn't installed, and the new streaming/
# async entry points degrade to the original non-streaming request when
# it's missing (see ANTHROPIC_SDK_AVAILABLE below).
try:
    from anthropic import Anthropic, AsyncAnthropic
    ANTHROPIC_SDK_AVAILABLE = True
except ImportError:
    ANTHROPIC_SDK_AVAILABLE = False

# "Prevent redundant commercial LLM calls if site weather/scores haven't
# changed" - 30 minutes, matching the TTL convention data_feeds.py already
# uses for its own "doesn't need to refresh often" feeds (its
# FORECAST_CACHE_TTL_SECONDS).
NARRATIVE_CACHE_TTL_SECONDS = 1800


# ---------------------------------------------------------------------------
# Global-workforce language support
# ---------------------------------------------------------------------------
# Display names used to build the "write in <language>" instruction sent to
# the Anthropic API. Kept as one generic name map (rather than a hand-written
# instruction string per language, as this used to be) so adding a language
# is a one-line addition here, not a repeated edit across every function
# that used to hardcode its own fr/en/ar/es dict.
LANGUAGE_DISPLAY_NAMES = {
    "fr": "French", "en": "English", "ar": "Modern Standard Arabic", "es": "Spanish",
    "zh": "Mandarin Chinese (Simplified script)", "ja": "Japanese", "hi": "Hindi",
    "ur": "Urdu", "da": "Danish", "nl": "Dutch", "no": "Norwegian", "sv": "Swedish",
    "pt": "Portuguese", "de": "German",
}

# Languages whose native script is not Latin - technical acronyms and units
# (WBGT, ACGIH, OEL, PM2.5, kW, cal/cm2, dBA...) are kept in Latin script for
# these, matching standard practice in each language's own technical and
# engineering documentation - the app already did this for Arabic and
# Spanish; this generalizes the same rule to every non-Latin-script language.
NON_LATIN_SCRIPT_LANGS = {"ar", "zh", "ja", "hi", "ur"}


def _language_instruction(lang: str) -> str:
    """Builds the 'write your response in <language>' instruction sent to
    the Anthropic API for generate_narrative()/generate_daily_briefing().
    Unknown language codes fall back to French, matching this app's
    existing default-language convention."""
    name = LANGUAGE_DISPLAY_NAMES.get(lang, "French")
    instruction = f"Write your response in {name}."
    if lang in NON_LATIN_SCRIPT_LANGS:
        instruction += (
            " Keep technical acronyms and units (e.g. WBGT, ACGIH, OEL, "
            "PM2.5, kW, cal/cm2) in Latin script, as is standard practice "
            "in technical and engineering documentation in this language."
        )
    return instruction


# ---------------------------------------------------------------------------
# Rule-based hierarchy of controls (always available, no API dependency)
# ---------------------------------------------------------------------------

def solar_controls(result: dict) -> list:
    band = result["risk_band"]
    controls = []
    if band in ("Moderate", "High", "Extreme"):
        controls += [
            "Shift high-exertion tracker/module installation to early morning or late afternoon windows",
            "Enforce ACGIH work/rest cycle per calculated action level; increase rest ratio if margin exceeded",
            "Mandatory shaded rest areas / cooling stations within 100m of active work fronts",
            "Buddy system + heat-illness spotters; mandatory electrolyte replacement schedule",
        ]
    if band in ("High", "Extreme"):
        controls += [
            "Escalate to HSE manager: consider suspending non-critical outdoor MEP tasks during peak GHI hours",
            "Reflective/ventilated PPE for crews working adjacent to panel rows (elevated radiant load)",
        ]
    if not controls:
        controls = ["Maintain standard heat-safety protocol; monitor GHI/temp trend for escalation"]
    return controls


def offshore_controls(result: dict) -> list:
    controls = []
    band = result["risk_band"]
    if band in ("Moderate", "High", "Extreme"):
        controls += [
            "Adjust welding/pipe-fitting shift rotations per Humidex band; shorten exposure intervals",
            "Increase hydration monitoring; enclosed-space heat retention areas need forced ventilation checks",
        ]
    if result["wind_risk_status"] != "Normal Operations":
        controls.append(f"Wind risk status: {result['wind_risk_status']}")
    if result["safety_override"]:
        controls.insert(0, "SAFETY OVERRIDE: suspend crane/lifting and welding ops until conditions recheck")
    if not controls:
        controls = ["Maintain standard marine HSE protocol; monitor wind/humidex trend"]
    return controls


def underground_controls(result: dict) -> list:
    controls = []
    band = result["risk_band"]
    if result["safety_override"]:
        controls.append("SAFETY OVERRIDE: halt non-essential high-voltage MEP cabling work until conditions recheck")
    if result["gas_exceeds"]:
        controls.append("CO OEL exceeded - evacuate face area, verify forced ventilation, re-test before re-entry")
    if result["dust_exceeds"]:
        controls.append("PM2.5 OEL exceeded - mandatory respiratory PPE upgrade, water suppression, re-test")
    if band in ("MODERATE", "HIGH", "CRITICAL"):
        controls.append("Reduce work/rest ratio for MEP electrical crews; rotate more frequently as heat trend rises")
    if band in ("HIGH", "CRITICAL"):
        controls.append("Prioritize temporary ventilation deployment ahead of permanent system commissioning")
    if not controls:
        controls = ["Maintain standard underground HSE protocol; continue OEL and heat monitoring cadence"]
    return controls


def high_rise_controls(result: dict) -> list:
    controls = []
    band = result["risk_band"]
    if result["safety_override"]:
        controls.append(
            "SAFETY OVERRIDE: suspend all crane lifts and external-wall/curtain-wall installation "
            "until scaled wind drops below the 30-knot threshold"
        )
    if band in ("HIGH", "CRITICAL"):
        controls += [
            "Notify tower crane operator and site HSE manager of current floor-level scaled wind readings",
            "Recheck tie-off points and suspended-access rigging before resuming work at height",
        ]
    if band == "MODERATE":
        controls.append("Delay non-critical curtain-wall/riser lifts to the next confirmed calm window")
    if not controls:
        controls = ["Maintain standard at-height wind-monitoring protocol; recheck anemometer feed each shift"]
    return controls


def data_center_controls(result: dict) -> list:
    controls = []
    if result["arc_flash_danger"]:
        controls.append(
            "DANGER: arc-flash incident energy exceeds max PPE rating at this load - "
            "de-energize equipment before any work; no PPE category permits live work"
        )
    if result["confined_armed_danger"]:
        controls.append(
            "Confined ceiling-void space + armed clean-agent suppression: disarm/isolate "
            "the system and atmosphere-test (O2/asphyxiant risk) before entry"
        )
    if result["thermal_differential"] >= 15.0:
        controls.append(
            "Hot/cold-aisle thermal differential elevated - rotate commissioning crews "
            "more frequently, hydrate, reduce continuous hot-aisle dwell time"
        )
    if result["safety_override"]:
        controls.insert(0, "SAFETY OVERRIDE: halt non-essential commissioning work in this zone until conditions are rechecked")
    if not controls:
        controls = ["Maintain standard data-center commissioning HSE protocol; continue thermal, arc-flash, and confined-space monitoring cadence"]
    return controls


def wind_energy_controls(result: dict) -> list:
    controls = []
    if result["safety_override"]:
        controls.append(
            "SAFETY OVERRIDE: halt all blade/nacelle access and crane operations "
            "until wind, lightning, or sea-state conditions clear"
        )
    if "STOP WORK" in result["lightning_status"]:
        controls.append(
            "30-30 rule triggered: evacuate exposed work-at-height positions immediately; "
            "do not resume outdoor work until 30 minutes after the last observed strike"
        )
    if result["risk_band"] in ("HIGH", "CRITICAL") and "STOP WORK" not in result["lightning_status"]:
        controls.append("Restrict blade/nacelle access to essential tasks only; recheck anemometer trend before each climb")
    if result["is_offshore"] and "Suspended" in result["ctv_transfer_status"]:
        controls.append("Suspend all crew-transfer-vessel personnel transfers until significant wave height drops below the transfer limit")
    if result["is_offshore"] and "Restricted" in result["ctv_transfer_status"]:
        controls.append("Limit CTV transfers to essential personnel only; brief crew on sea-state trend")
    if not controls:
        controls = ["Maintain standard wind-energy HSE protocol; continue hub-height wind, lightning, and sea-state monitoring"]
    return controls


def mining_quarrying_controls(result: dict) -> list:
    controls = []
    if result["safety_override"]:
        controls.insert(0, "SAFETY OVERRIDE: halt exposure until silica, noise, or vibration levels are brought under control")
    if result["silica_exceeds_oel"]:
        controls.append(
            "Respirable crystalline silica exceeds the OEL - mandatory water suppression/wet-cutting, "
            "upgrade respiratory PPE, rotate crews away from the quarry face"
        )
    if result["noise_dose_pct"] >= 100:
        controls.append(
            f"Noise dose at {result['noise_dose_pct']}% of the permissible 8-hour limit - "
            "mandatory hearing protection, reduce continuous exposure duration, isolate/enclose plant noise sources where feasible"
        )
    if result["vibration_exceeds_limit"]:
        controls.append(
            "Whole-body vibration A(8) exceeds the EU exposure limit value - remove operator from "
            "the machine immediately, inspect seat/suspension, reduce daily operating hours"
        )
    elif result["vibration_exceeds_action"]:
        controls.append("Whole-body vibration A(8) exceeds the action value - schedule maintenance on seat/suspension, monitor exposure hours")
    if not controls:
        controls = ["Maintain standard mining/quarrying HSE protocol; continue silica, noise, and vibration monitoring cadence"]
    return controls


def marine_port_controls(result: dict) -> list:
    controls = []
    if result["safety_override"]:
        controls.insert(0, "SAFETY OVERRIDE: halt marine/port access work until tide clearance or hardware capacity conditions are rechecked")
    if result["tide_clearance_margin_m"] <= 0.3:
        controls.append("Tide clearance margin critical - halt underside/pile-driving access work until tide recedes to a safe margin")
    elif result["tide_clearance_margin_m"] <= 0.8:
        controls.append("Tide clearance margin restricted - limit access to essential monitored tasks, recheck tide tables before each shift")
    if result["night_amplified"]:
        controls.append("Task-area illuminance below the OSHA 1926.56 minimum for night operations - deploy additional lighting before resuming work")
    if result["hardware_remaining_capacity_pct"] < 85.0:
        controls.append(
            f"Splash-zone hardware estimated at {result['hardware_remaining_capacity_pct']}% of rated capacity - "
            "schedule a certified structural inspection before continued use; consider derating safe working load"
        )
    if not controls:
        controls = ["Maintain standard marine/port HSE protocol; continue tide, lighting, and hardware-condition monitoring"]
    return controls


def heat_stress_controls(result: dict) -> list:
    """HSE audit corrective action - Occupational Heat-Stress Upgrade
    (calculate_iso7243_heat_stress()). Recommendations are driven by the
    same fields the advanced heat-stress panel already displays
    (recommended_work_rest_ratio, requires_physiological_monitoring), so
    there is no second, disconnected judgment call here - just plain-
    language translation of what the calculation already determined."""
    controls = []
    if result["safety_override"]:
        if result.get("requires_physiological_monitoring"):
            controls.insert(0, "SAFETY OVERRIDE: vapor-barrier/limited-use PPE requires direct physiological "
                                "monitoring (e.g. core temperature, heart-rate recovery) - a WBGT table lookup "
                                "alone is not sufficient authorization to continue work in this ensemble")
        else:
            controls.insert(0, "STOP WORK: no ACGIH-compliant work/rest ratio exists at this workload/clothing/"
                                "acclimatization combination, even at 25/75 - reduce workload category, change "
                                "clothing, or wait for cooler conditions before resuming")
    elif result.get("recommended_work_rest_ratio") not in (None, "100/0"):
        controls.append(
            f"Adopt a {result['recommended_work_rest_ratio']} work/rest cycle to stay within the ACGIH TLV "
            f"action limit for this workload category and clothing ensemble"
        )
    if not result.get("acclimatized"):
        controls.append("Worker is not marked as heat-acclimatized - apply a graduated acclimatization schedule "
                         "(ACGIH recommends progressive exposure over ~1-2 weeks) before assigning full workload")
    if not controls:
        controls = ["Maintain standard heat-stress protocol; recheck WBGT/clothing/workload if conditions change"]
    return controls


CONTROLS_MAP = {
    "Solar (Desert)": solar_controls,
    "Offshore (Marine)": offshore_controls,
    "Underground (Tunnel/Metro)": underground_controls,
    "High-Rise (Vertical Urban)": high_rise_controls,
    "Data Center (Controlled Critical Environment)": data_center_controls,
    "Wind Energy (Onshore/Offshore)": wind_energy_controls,
    "Mining & Quarrying": mining_quarrying_controls,
    "Marine & Port Construction": marine_port_controls,
    "Occupational Heat Stress (ISO 7243 / ACGIH TLV)": heat_stress_controls,
}


def get_controls(result: dict) -> list:
    return CONTROLS_MAP[result["module"]](result)


def get_regulatory_references(result: dict) -> list[dict]:
    """Curated citations (regulatory_references.py) for this result's module.
    Names the applicable standards bodies/documents - never reproduces their
    text. See regulatory_references.py for the full rationale."""
    return get_references(result.get("module", ""))


def get_bibliography() -> list[dict]:
    """General professional reference texts, cited by title/author/publisher
    only (see regulatory_references.py)."""
    return get_further_reading()


# ---------------------------------------------------------------------------
# Optional LLM narrative layer (Anthropic API)
# ---------------------------------------------------------------------------

def _worker_strain_instruction(worker_strain_summary: list[dict] | None) -> str:
    """Builds the 'cross-reference live biometric strain' instruction block.
    worker_strain_summary is a list of risk_engine.calculate_physiological_
    strain() result dicts (or an equivalent minimal shape with at least
    'status'/'pct_hr_max') for whichever anonymized workers currently have
    a reading. None/empty means no wearable data is active for this
    assessment - the model is told that explicitly rather than left to
    guess, so it never fabricates a biometric reading that wasn't supplied."""
    if not worker_strain_summary:
        return (
            "No live worker biometric/wearable data is available for this assessment - "
            "base the action plan on environmental readings only."
        )
    critical = [w for w in worker_strain_summary if w.get("status") == "CRITICAL"]
    warning = [w for w in worker_strain_summary if w.get("status") == "WARNING"]
    lines = [
        f"- {w.get('worker_id', 'Worker')}: {w.get('status')} ({w.get('pct_hr_max', '?')}% max HR, "
        f"est. core temp {w.get('estimated_core_temp_c', '?')}C)"
        for w in worker_strain_summary
    ]
    priority_note = (
        "AT LEAST ONE WORKER IS AT CRITICAL PHYSIOLOGICAL STRAIN RIGHT NOW. "
        "Prioritize an immediate human-strain response (stop work / rotate / cool down "
        "that individual) as the single most urgent action, ranked ABOVE any raw "
        "environmental WBGT/Humidex-only recommendation - real-time cardiac load takes "
        "precedence over a meteorological threshold that hasn't yet been crossed."
        if critical else
        "One or more workers are at WARNING-level physiological strain. Reference this "
        "directly alongside the environmental reading and recommend closer monitoring or "
        "an earlier rotation than the environmental threshold alone would suggest."
        if warning else
        "All monitored workers are currently within SAFE physiological strain - you may "
        "still mention this briefly as reassuring context."
    )
    return (
        "LIVE WORKER BIOMETRIC / WEARABLE DATA (anonymized profile markers only):\n"
        + "\n".join(lines) + f"\n\n{priority_note}"
    )


def _build_narrative_request(
    result: dict,
    controls: list,
    lang: str,
    enable_web_search: bool = False,
    worker_strain_summary: list[dict] | None = None,
) -> tuple[str, dict]:
    """Builds the exact prompt string and any extra request_body fields
    (currently just 'tools' when enable_web_search=True) shared by every
    narrative-generating entry point (the original synchronous call, the
    cached wrapper, the streaming generator, and the background async
    job) - extracted so all four stay byte-for-byte consistent instead of
    four copies of the same prompt logic drifting apart over time.
    Returns (prompt, extra_request_fields)."""
    language_instruction = _language_instruction(lang)

    references = get_references(result.get("module", ""))
    references_text = "\n".join(
        f"- {ref['region']} / {ref['body']}: {ref['doc']}" + (f" ({ref['url']})" if ref.get("url") else "")
        for ref in references
    ) or "- No pre-verified references available for this module."

    jurisdiction_label = result.get("regulatory_profile_label", "")
    jurisdiction_instruction = (
        f"This assessment was evaluated under the following ACTIVE regulatory "
        f"jurisdiction: {jurisdiction_label}. When a recommendation or "
        "stop-work condition stems from a jurisdiction-specific rule (e.g. a "
        "mandatory thermal/heat rotation, a statutory midday outdoor-work "
        "ban, a Humidex or Wind Chill threshold, a UV/sun-protection "
        "trigger, or an isolated/remote-worker communication requirement), "
        "name the specific regulatory body by its real name (for example: "
        "'According to CNESST guidelines, a mandatory thermal rotation is "
        "required...', 'Per HSE COSHH exposure limits...', 'Under Safe Work "
        "Australia's model WHS Regulations...'). Only name a body/framework "
        "that appears here or in the verified reference list below - never "
        "invent one."
        if jurisdiction_label else
        "No active regulatory jurisdiction label was supplied with this "
        "assessment - do not name a specific regulatory body; refer to "
        "applicable local and international HSE standards generally."
    )

    search_instruction = (
        "You have a web_search tool available. You may use it (a few searches "
        "at most) to check for current, jurisdiction-specific guidance or "
        "recent amendments relevant to this assessment. If you use it, cite "
        "the specific source name and URL you found - never state a figure, "
        "clause, or threshold from a search result without naming where it "
        "came from."
        if enable_web_search else
        "Do not search the web. Base your citations only on the verified "
        "reference list supplied below."
    )

    worker_strain_instruction = _worker_strain_instruction(worker_strain_summary)

    prompt = (
        "You are an HSE risk communication assistant grounded in an authentic "
        "safety-culture philosophy: compliance is the OUTPUT of a genuine "
        "safety culture, not administrative theater, and the real test of "
        "that culture is whether leadership chooses to control the risk or "
        "cut the cost when the two are in tension.\n\n"
        "Given this structured construction risk assessment output "
        "(JSON-like), write a concise operational briefing for an HSE "
        "manager: risk level, primary hazard, the single most urgent "
        "action, and a stop-work condition if applicable. Be direct, "
        "professional, no fluff.\n\n"
        "CITATION RULES (do not violate these):\n"
        "- Only cite the standards bodies/documents listed below, or ones "
        "you find via live web search and can name with a real URL.\n"
        "- NEVER invent a named methodology, 'principles', framework, or "
        "clause/section number that you are not certain is real. If unsure, "
        "name the standards body generally (e.g. 'consult applicable OSHA "
        "guidance') rather than inventing a specific citation.\n"
        f"- {search_instruction}\n\n"
        f"VERIFIED REFERENCES FOR THIS MODULE:\n{references_text}\n\n"
        f"ACTIVE JURISDICTION:\n{jurisdiction_instruction}\n\n"
        f"{worker_strain_instruction}\n\n"
        f"{language_instruction}\n\n"
        f"DATA: {result}\n\nRECOMMENDED CONTROLS: {controls}"
    )

    extra: dict = {}
    if enable_web_search:
        extra["tools"] = [{"type": "web_search_20250305", "name": "web_search", "max_uses": WEB_SEARCH_MAX_USES}]
    return prompt, extra


def generate_narrative(
    result: dict,
    controls: list,
    api_key: str,
    lang: str = "fr",
    enable_web_search: bool = False,
    worker_strain_summary: list[dict] | None = None,
) -> str:
    """
    Calls the Anthropic API to turn the structured risk_engine output into a
    short HSE-manager-facing narrative. Falls back gracefully if no key is
    provided or the call fails - the app must never depend on this to function.

    lang: UI language code ("fr" default, or "en"). Per project guidelines the
    app defaults to French, so the AI briefing is requested in French unless
    the user has switched to English. The underlying data/controls stay in
    English (they come straight from the transparent risk_engine/ai_advisor
    logic) - only the generated narrative text is localized.

    enable_web_search: opt-in only (costs extra API usage/latency). When True
    and an api_key is supplied, enables Claude's built-in web_search tool so
    the model can look up current, jurisdiction-specific guidance live and
    cite real URLs, on top of (never instead of) the verified reference list
    below. This reuses the same Anthropic API key already required for the
    narrative - no separate search API key needed.

    worker_strain_summary: optional list of risk_engine.
    calculate_physiological_strain() results for currently-monitored
    anonymized workers - when supplied, the model is instructed to
    cross-reference real-time cardiac load against the environmental
    WBGT/Humidex reading and prioritize a CRITICAL/WARNING biometric
    signal over a raw meteorological threshold. None (the default) keeps
    every pre-existing call site's behavior byte-for-byte unchanged.

    Grounding note: the prompt supplies the model with the EXACT verified
    regulatory references for this module (from regulatory_references.py)
    and explicitly forbids inventing named methodologies, "principles",
    clause numbers, or frameworks beyond what's supplied or found via live
    search. An earlier version of this prompt instructed the model to
    invoke "Roger Bauer's... risk-analysis principles" as if it were an
    established methodology - that was a fabrication risk (same category of
    problem regulatory_references.py exists to prevent) and has been
    removed entirely.
    """
    if not api_key:
        return _fallback_narrative(result, controls, lang)

    prompt, extra = _build_narrative_request(result, controls, lang, enable_web_search, worker_strain_summary)
    request_body = {
        "model": MODEL,
        "max_tokens": 700,
        "messages": [{"role": "user", "content": prompt}],
        **extra,
    }

    try:
        resp = requests.post(
            ANTHROPIC_URL,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json=request_body,
            timeout=40 if enable_web_search else 20,
        )
        resp.raise_for_status()
        data = resp.json()
        text_parts = [b["text"] for b in data.get("content", []) if b.get("type") == "text"]
        return "\n".join(text_parts).strip() or _fallback_narrative(result, controls, lang)
    except Exception as e:
        return _fallback_narrative(result, controls, lang) + f"\n\n[AI narrative unavailable: {e}]"


@st.cache_data(ttl=NARRATIVE_CACHE_TTL_SECONDS, show_spinner=False)
def generate_narrative_cached(
    result: dict,
    controls: list,
    _api_key: str,
    lang: str = "fr",
    enable_web_search: bool = False,
    worker_strain_summary: list[dict] | None = None,
) -> str:
    """
    Performance layer: identical contract to generate_narrative(), wrapped
    in st.cache_data with a 30-minute TTL so repeated identical requests
    (same site result/controls/language/jurisdiction/worker-strain
    snapshot within that window) return instantly with zero redundant
    Anthropic API calls - directly answers "prevent redundant commercial
    LLM calls if site weather/scores haven't changed".

    The api_key parameter is named with a leading underscore (Streamlit's
    documented convention for "use this value, but don't hash it into the
    cache key") - the narrative text a given (result, controls, lang,
    worker_strain_summary) combination produces doesn't depend on which
    valid key paid for the call, and excluding it also avoids ever
    embedding a partial key into Streamlit's cache-key bookkeeping.

    This is the NON-streaming path - see generate_narrative_stream_chunks()
    for the live token-by-token rendering path, which deliberately always
    calls the API fresh (caching a stream the user is actively watching
    token-by-token defeats the point of showing it as a stream)."""
    return generate_narrative(result, controls, _api_key, lang, enable_web_search, worker_strain_summary)


# ---------------------------------------------------------------------------
# Token streaming (renders word-by-word instead of freezing the interface)
# ---------------------------------------------------------------------------
# Uses the `anthropic` SDK's synchronous streaming client - a plain
# generator, meant to be handed directly to Streamlit's own st.write_stream()
# in app.py, which iterates it and updates the display incrementally as
# each chunk arrives, then returns the fully concatenated text. This is
# the real stream=True request/response path (Server-Sent Events under
# the hood), not a fake client-side typewriter effect over an already-
# complete string.

def generate_narrative_stream_chunks(
    result: dict,
    controls: list,
    api_key: str,
    lang: str = "fr",
    enable_web_search: bool = False,
    worker_strain_summary: list[dict] | None = None,
):
    """
    Generator yielding narrative text chunks as they stream in from the
    Anthropic API (stream=True). Intended usage in app.py:
        narrative = st.write_stream(generate_narrative_stream_chunks(...))
    which renders each chunk live and returns the joined final string.

    Falls back to yielding the complete offline/fallback narrative as a
    single chunk (st.write_stream handles a single-item generator fine)
    when no api_key is supplied or the `anthropic` SDK isn't installed -
    streaming is a progressive rendering enhancement, never a hard
    requirement for the narrative to appear at all.

    Deliberately NOT cached (see generate_narrative_cached's docstring) -
    every call here is a fresh, live API request, because the whole point
    of showing a stream is that the user is watching it happen right now.
    """
    if not api_key or not ANTHROPIC_SDK_AVAILABLE:
        yield generate_narrative(result, controls, api_key, lang, enable_web_search, worker_strain_summary)
        return

    prompt, extra = _build_narrative_request(result, controls, lang, enable_web_search, worker_strain_summary)
    try:
        client = Anthropic(api_key=api_key)
        kwargs = dict(model=MODEL, max_tokens=700, messages=[{"role": "user", "content": prompt}], **extra)
        got_any_text = False
        with client.messages.stream(**kwargs) as stream:
            for text in stream.text_stream:
                got_any_text = True
                yield text
        if not got_any_text:
            yield _fallback_narrative(result, controls, lang)
    except Exception as e:  # noqa: BLE001 - never let a streaming failure blank the page
        yield _fallback_narrative(result, controls, lang) + f"\n\n[AI narrative unavailable: {e}]"


# ---------------------------------------------------------------------------
# Background async generation (AsyncAnthropic on a worker thread), so the
# rest of the page - including analytics.py's charts, already rendered
# earlier in the same script run - stays interactive while the narrative
# generates.
# ---------------------------------------------------------------------------
# HONEST DESIGN NOTE: Streamlit's script execution model reruns the whole
# script top-to-bottom per interaction and is single-threaded within that
# run - a plain synchronous (or even a bare `await`ed async) API call still
# blocks that entire run until it returns, identical to the old
# requests.post() behavior. A background Python thread is what actually
# makes the rest of the page interactive during generation: the button
# handler starts the thread and returns immediately, and a
# st.fragment(run_every=...) poller (see app.py) reruns ONLY itself on a
# timer to display newly-arrived tokens, never forcing the whole page (and
# its already-rendered analytics charts) to rerun. AsyncAnthropic is the
# client actually used to talk to the API inside that thread, per the
# request - the thread is what delivers the non-blocking UX, AsyncAnthropic
# is what performs the (concurrency-friendly) call within it.

class NarrativeStreamJob:
    """Thread-safe handle for one background streaming narrative job.
    The worker thread (see _run_stream_worker) only ever writes to
    `_queue`/`done`/`error`/`full_text`; app.py's st.fragment poller
    (running on Streamlit's main thread) only ever reads them via
    pull_available_tokens()."""

    def __init__(self) -> None:
        self._queue: "queue.Queue[str]" = queue.Queue()
        self.done = False
        self.error: str | None = None
        self.full_text = ""

    def pull_available_tokens(self) -> list[str]:
        """Drains whatever chunks have arrived since the last poll -
        non-blocking, safe to call every fragment tick even if nothing
        new has arrived yet."""
        chunks = []
        while True:
            try:
                chunks.append(self._queue.get_nowait())
            except queue.Empty:
                break
        return chunks


def _run_stream_worker(job: NarrativeStreamJob, prompt: str, extra: dict, api_key: str) -> None:
    """Runs on a background thread - never on Streamlit's main script-run
    thread. Drives AsyncAnthropic via asyncio.run() inside this dedicated
    thread (each thread gets its own event loop this way, which is the
    supported pattern for running asyncio code outside a thread that
    already has a running loop, like Streamlit's main thread might)."""
    async def _consume() -> None:
        client = AsyncAnthropic(api_key=api_key)
        try:
            kwargs = dict(model=MODEL, max_tokens=700, messages=[{"role": "user", "content": prompt}], **extra)
            async with client.messages.stream(**kwargs) as stream:
                async for text in stream.text_stream:
                    job._queue.put(text)
                    job.full_text += text
        finally:
            await client.close()

    try:
        asyncio.run(_consume())
    except Exception as e:  # noqa: BLE001 - surfaced to the poller, never crashes the thread silently
        job.error = str(e)
    finally:
        job.done = True


def start_narrative_background_job(
    result: dict,
    controls: list,
    api_key: str,
    lang: str = "fr",
    enable_web_search: bool = False,
    worker_strain_summary: list[dict] | None = None,
) -> "NarrativeStreamJob | None":
    """
    Kicks off streaming narrative generation on a background thread and
    returns immediately with a job handle for app.py to poll from a
    st.fragment(run_every=...). Returns None (caller should fall back to
    generate_narrative_cached()/generate_narrative_stream_chunks()) when
    no api_key is supplied or the `anthropic` SDK isn't installed -
    background generation is a progressive-enhancement layer, never a
    hard requirement, matching this module's offline-first guarantee.
    """
    if not api_key or not ANTHROPIC_SDK_AVAILABLE:
        return None
    prompt, extra = _build_narrative_request(result, controls, lang, enable_web_search, worker_strain_summary)
    job = NarrativeStreamJob()
    thread = threading.Thread(target=_run_stream_worker, args=(job, prompt, extra, api_key), daemon=True)
    thread.start()
    return job


_FALLBACK_NARRATIVE_DEFAULT_CONTROL = {
    "en": "Maintain standard protocol",
    "fr": "Maintenir le protocole standard",
    "ar": "الحفاظ على البروتوكول القياسي",
    "es": "Mantener el protocolo estándar",
    "zh": "维持标准操作规程",
    "ja": "標準プロトコルを維持する",
    "hi": "मानक प्रोटोकॉल बनाए रखें",
    "ur": "معیاری پروٹوکول برقرار رکھیں",
    "da": "Oprethold standardprotokol",
    "nl": "Standaardprotocol handhaven",
    "no": "Oppretthold standardprotokoll",
    "sv": "Upprätthåll standardprotokoll",
    "pt": "Manter o protocolo padrão",
    "de": "Standardprotokoll beibehalten",
}

# {band}/{hazard}/{top_control}/{regulatory_basis} placeholders - main body
# only, the elevated-risk leadership-decision sentence is a separate template
# below so it can be appended (with no gap for languages that don't want a
# leading space quirk) only when the risk band actually warrants it.
_FALLBACK_NARRATIVE_MAIN = {
    "en": "Risk level: {band}. Primary hazard: {hazard}. Most urgent action: "
          "{top_control} Regulatory basis: {regulatory_basis}. Verify controls "
          "at the work front before release; stop work if the trigger or "
          "safety override remains active.",
    "fr": "Niveau de risque : {band}. Danger principal : {hazard}. Action la "
          "plus urgente : {top_control} Base réglementaire : {regulatory_basis}. "
          "Vérifier les mesures au front de travail avant reprise ; arrêter si "
          "le seuil ou l'override de sécurité reste actif.",
    "ar": "مستوى الخطورة: {band}. الخطر الرئيسي: {hazard}. الإجراء الأكثر "
          "إلحاحاً: {top_control} الأساس التنظيمي: {regulatory_basis}. تحقق من "
          "الإجراءات في موقع العمل قبل السماح بالاستئناف؛ أوقف العمل إذا ظل "
          "المحفّز أو تجاوز السلامة نشطاً.",
    "es": "Nivel de riesgo: {band}. Peligro principal: {hazard}. Acción más "
          "urgente: {top_control} Base normativa: {regulatory_basis}. Verifique "
          "los controles en el frente de trabajo antes de reanudar; detenga el "
          "trabajo si el disparador o la anulación de seguridad permanece activo.",
    "zh": "风险等级：{band}。主要危害：{hazard}。最紧急的措施：{top_control} "
          "法规依据：{regulatory_basis}。在恢复作业前请核实作业面的管控措施；"
          "如触发条件或安全超限仍然有效，应立即停工。",
    "ja": "リスクレベル：{band}。主な危険：{hazard}。最も緊急性の高い対応："
          "{top_control} 規制根拠：{regulatory_basis}。作業を再開する前に現場で"
          "管理策を確認してください。トリガーまたは安全オーバーライドが依然として"
          "有効な場合は作業を中止してください。",
    "hi": "जोखिम स्तर: {band}। प्रमुख खतरा: {hazard}। सबसे जरूरी कार्रवाई: "
          "{top_control} नियामक आधार: {regulatory_basis}। कार्य फिर से शुरू करने "
          "से पहले कार्यस्थल पर नियंत्रण उपायों की पुष्टि करें; यदि ट्रिगर या "
          "सुरक्षा ओवरराइड सक्रिय बना रहे तो कार्य रोक दें।",
    "ur": "خطرے کی سطح: {band}۔ بنیادی خطرہ: {hazard}۔ سب سے زیادہ فوری اقدام: "
          "{top_control} ریگولیٹری بنیاد: {regulatory_basis}۔ کام دوبارہ شروع "
          "کرنے سے پہلے کام کی جگہ پر حفاظتی اقدامات کی تصدیق کریں؛ اگر محرک یا "
          "حفاظتی اوور رائیڈ فعال رہے تو کام روک دیں۔",
    "da": "Risikoniveau: {band}. Primær fare: {hazard}. Mest presserende "
          "handling: {top_control} Lovgivningsmæssigt grundlag: "
          "{regulatory_basis}. Kontrollér foranstaltningerne på arbejdsstedet, "
          "før arbejdet genoptages; stop arbejdet, hvis udløseren eller "
          "sikkerhedsoverskridelsen forbliver aktiv.",
    "nl": "Risiconiveau: {band}. Primair gevaar: {hazard}. Meest urgente actie: "
          "{top_control} Wettelijke basis: {regulatory_basis}. Controleer de "
          "beheersmaatregelen op de werkplek voordat het werk wordt hervat; "
          "staak het werk als de trigger of veiligheidsoverschrijding actief blijft.",
    "no": "Risikonivå: {band}. Primær fare: {hazard}. Mest presserende tiltak: "
          "{top_control} Regelverksgrunnlag: {regulatory_basis}. Kontroller "
          "tiltakene på arbeidsstedet før arbeidet gjenopptas; stans arbeidet "
          "hvis utløseren eller sikkerhetsoverstyringen fortsatt er aktiv.",
    "sv": "Risknivå: {band}. Primär fara: {hazard}. Mest brådskande åtgärd: "
          "{top_control} Regelverksgrund: {regulatory_basis}. Kontrollera "
          "åtgärderna på arbetsplatsen innan arbetet återupptas; stoppa arbetet "
          "om utlösaren eller säkerhetsöverskridandet fortfarande är aktivt.",
    "pt": "Nível de risco: {band}. Perigo principal: {hazard}. Ação mais "
          "urgente: {top_control} Base regulatória: {regulatory_basis}. "
          "Verifique os controles na frente de trabalho antes da liberação; "
          "interrompa o trabalho se o gatilho ou a anulação de segurança "
          "permanecer ativo.",
    "de": "Risikostufe: {band}. Hauptgefahr: {hazard}. Dringendste Maßnahme: "
          "{top_control} Rechtliche Grundlage: {regulatory_basis}. Überprüfen "
          "Sie die Kontrollmaßnahmen vor Ort, bevor die Arbeit freigegeben wird; "
          "stoppen Sie die Arbeit, wenn der Auslöser oder die "
          "Sicherheitsüberschreitung weiterhin aktiv ist.",
}

_FALLBACK_NARRATIVE_ELEVATED_SUFFIX = {
    "en": " This is a leadership decision, not a paperwork exercise: controlling "
          "this risk now is what an authentic safety culture looks like in practice.",
    "fr": " Ceci est une décision de leadership, pas un exercice administratif : "
          "contrôler ce risque maintenant, c'est ce à quoi ressemble une culture "
          "de sécurité authentique dans la pratique.",
    "ar": " هذا قرار قيادي وليس إجراءً إدارياً شكلياً: التحكم في هذا الخطر الآن "
          "هو ما تبدو عليه ثقافة السلامة الأصيلة في الممارسة.",
    "es": " Esta es una decisión de liderazgo, no un trámite administrativo: "
          "controlar este riesgo ahora es lo que se ve una cultura de seguridad "
          "auténtica en la práctica.",
    "zh": "这是一项领导层决策，而非纸面文书：现在控制这一风险，才是真正安全文化在"
          "实践中的体现。",
    "ja": "これは書類上の手続きではなく、経営層の決断です。今この危険を管理する"
          "ことこそが、真の安全文化の実践的な姿です。",
    "hi": " यह एक नेतृत्व का निर्णय है, कागजी कार्यवाही नहीं: अभी इस जोखिम को "
          "नियंत्रित करना ही एक वास्तविक सुरक्षा संस्कृति के व्यवहार में दिखने "
          "का तरीका है।",
    "ur": " یہ ایک قائدانہ فیصلہ ہے، کاغذی کارروائی نہیں: ابھی اس خطرے پر قابو "
          "پانا ہی ایک حقیقی حفاظتی ثقافت کی عملی شکل ہے۔",
    "da": " Dette er en ledelsesbeslutning, ikke en administrativ øvelse: at "
          "kontrollere denne risiko nu er, hvad en autentisk sikkerhedskultur "
          "ser ud som i praksis.",
    "nl": " Dit is een leiderschapsbeslissing, geen administratieve formaliteit: "
          "dit risico nu beheersen is wat een authentieke veiligheidscultuur in "
          "de praktijk betekent.",
    "no": " Dette er en lederbeslutning, ikke en papirøvelse: å kontrollere denne "
          "risikoen nå er hva en autentisk sikkerhetskultur ser ut som i praksis.",
    "sv": " Detta är ett ledarskapsbeslut, inte en pappersövning: att kontrollera "
          "denna risk nu är vad en genuin säkerhetskultur ser ut som i praktiken.",
    "pt": " Esta é uma decisão de liderança, não um exercício burocrático: "
          "controlar este risco agora é o que uma cultura de segurança autêntica "
          "parece na prática.",
    "de": " Dies ist eine Führungsentscheidung, kein bürokratischer Vorgang: "
          "dieses Risiko jetzt zu kontrollieren, ist das, was eine authentische "
          "Sicherheitskultur in der Praxis bedeutet.",
}


def _fallback_narrative(result: dict, controls: list, lang: str = "fr") -> str:
    """
    Offline/no-key fallback narrative, localized for all 14 supported UI
    languages; the underlying risk_band/primary_hazard/controls values
    themselves stay in English (they're the transparent engine's raw
    vocabulary). Unknown language codes fall back to French, matching this
    app's existing default-language convention.

    For elevated risk bands, appends a short line reflecting the safety
    culture principle above: this is the moment where leadership either
    controls the risk or cuts the cost, and that choice - not the paperwork -
    is what the AI briefing is here to surface.

    The regulatory basis line now leads with the ACTIVE jurisdiction (e.g.
    "Canada (OHS / CNESST)") when the result carries one, before the
    module's general citation list - so even the offline, no-API-key
    narrative names the specific active jurisdiction, not just a generic
    module reference list.
    """
    band = result.get("risk_band", "Unknown")
    hazard = result.get("primary_hazard", "")
    default_control = _FALLBACK_NARRATIVE_DEFAULT_CONTROL.get(
        lang, _FALLBACK_NARRATIVE_DEFAULT_CONTROL["fr"]
    )
    top_control = controls[0] if controls else default_control

    elevated = str(band).upper() in ("HIGH", "EXTREME", "CRITICAL", "EXTREME (DANGER)")

    regulatory_basis = _regulatory_basis(result)

    template = _FALLBACK_NARRATIVE_MAIN.get(lang, _FALLBACK_NARRATIVE_MAIN["fr"])
    text = template.format(
        band=band, hazard=hazard, top_control=top_control, regulatory_basis=regulatory_basis
    )
    if elevated:
        text += _FALLBACK_NARRATIVE_ELEVATED_SUFFIX.get(lang, _FALLBACK_NARRATIVE_ELEVATED_SUFFIX["fr"])
    return text


def _regulatory_basis(result: dict) -> str:
    """Return named frameworks relevant to the assessed environment. Leads
    with the ACTIVE jurisdiction's own label (result['regulatory_profile_label'],
    e.g. 'Canada (OHS / CNESST)') when present, so requirement #3 (name the
    specific active jurisdiction, e.g. 'According to CNESST guidelines...')
    is honored even in the offline no-API-key narrative - then appends the
    module's general citation bodies from the single verified citation list
    in regulatory_references.py (never a separate hardcoded list), so this
    stays consistent with the full Regulatory References section and never
    names an unverified framework."""
    jurisdiction_label = result.get("regulatory_profile_label")

    refs = get_references(result.get("module", ""))
    bodies = []
    for ref in refs:
        if ref["body"] not in bodies:
            bodies.append(ref["body"])

    if jurisdiction_label:
        rest = "; ".join(b for b in bodies if b not in jurisdiction_label)
        return f"{jurisdiction_label}" + (f"; {rest}" if rest else "")
    return "; ".join(bodies) if bodies else "consult applicable local and international HSE standards"


# ---------------------------------------------------------------------------
# Module 5b: Offline-first fault tolerance - shared error classification
# ---------------------------------------------------------------------------
# generate_narrative() above already never lets an API failure break the
# app (it always falls back to _fallback_narrative()). This helper adds the
# one thing that was still generic ("[AI narrative unavailable: <exception>]"):
# telling the caller (app.py's toast) *what kind* of failure this was, so a
# site foreman on a spotty cellular connection sees "poor network coverage"
# rather than a raw Python exception string.
def classify_api_error(exc: Exception) -> str:
    """Returns one of 'network', 'timeout', 'auth', 'rate_limit', 'other' -
    used by app.py to pick the right offline-mode toast message."""
    text = str(exc).lower()
    if isinstance(exc, requests.exceptions.Timeout) or "timeout" in text:
        return "timeout"
    if isinstance(exc, (requests.exceptions.ConnectionError, requests.exceptions.SSLError)):
        return "network"
    if "401" in text or "invalid x-api-key" in text or "authentication" in text:
        return "auth"
    if "429" in text or "rate limit" in text:
        return "rate_limit"
    return "other"


# ---------------------------------------------------------------------------
# Module 1 (part 2): Instant narrative translation, with an optional Gulf/
# Egyptian Arabic dialect option
# ---------------------------------------------------------------------------

ARABIC_DIALECT_INSTRUCTIONS = {
    "msa": "Use Modern Standard Arabic (Fusha), the neutral register appropriate "
           "for official written HSE communication.",
    "gulf": "Use Gulf Arabic phrasing and vocabulary suitable for construction "
            "sites in the UAE/Kuwait/wider Gulf region, while keeping technical "
            "terms and safety-critical instructions unambiguous - clarity to a "
            "diverse multinational workforce takes priority over strict dialect "
            "purity.",
    "egyptian": "Use Egyptian Arabic phrasing and vocabulary common among "
                "construction crews from Egypt, while keeping technical terms "
                "and safety-critical instructions unambiguous - clarity to a "
                "diverse multinational workforce takes priority over strict "
                "dialect purity.",
}

_TRANSLATE_TARGET_NAMES = LANGUAGE_DISPLAY_NAMES


def translate_narrative(text: str, target_lang: str, api_key: str | None,
                         dialect: str = "msa") -> dict:
    """
    Translates an already-generated AI briefing into another language on
    demand - e.g. an HSE manager reads the French briefing, then translates
    it to Arabic (optionally in Gulf or Egyptian dialect) to read aloud to
    the crew, without re-running the whole risk assessment.

    HONEST LIMITATION: this is a live-API-only feature. There is no
    reliable, production-safe offline translation path bundled with this
    app (a real offline MT model is far too heavy for this deployment, and
    unofficial free-translate APIs are not something a safety tool should
    depend on silently). If no key is supplied or the call fails, this
    returns the ORIGINAL text unchanged with an explicit note - it never
    fabricates a translation or silently returns text in the wrong
    language, since that would be actively dangerous for a safety briefing.

    Returns {"text": str, "translated": bool, "error_kind": str | None}.
    """
    if target_lang not in _TRANSLATE_TARGET_NAMES:
        return {"text": text, "translated": False, "error_kind": "unsupported_language"}

    if not api_key:
        return {"text": text, "translated": False, "error_kind": "no_api_key"}

    target_name = _TRANSLATE_TARGET_NAMES[target_lang]
    dialect_note = ""
    if target_lang == "ar":
        dialect_note = "\n\n" + ARABIC_DIALECT_INSTRUCTIONS.get(dialect, ARABIC_DIALECT_INSTRUCTIONS["msa"])

    prompt = (
        f"Translate the following HSE safety briefing into {target_name}. "
        "Preserve all numbers, units, and technical acronyms (WBGT, ACGIH, OEL, "
        "PM2.5, kW, cal/cm2, dBA, etc.) exactly as given - do not convert units. "
        "Output ONLY the translation, no preamble, no explanation."
        f"{dialect_note}\n\n"
        f"TEXT TO TRANSLATE:\n{text}"
    )

    try:
        resp = requests.post(
            ANTHROPIC_URL,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={"model": MODEL, "max_tokens": 700, "messages": [{"role": "user", "content": prompt}]},
            timeout=20,
        )
        resp.raise_for_status()
        data = resp.json()
        parts = [b["text"] for b in data.get("content", []) if b.get("type") == "text"]
        translated = "\n".join(parts).strip()
        if not translated:
            return {"text": text, "translated": False, "error_kind": "empty_response"}
        return {"text": translated, "translated": True, "error_kind": None}
    except Exception as exc:  # noqa: BLE001
        return {"text": text, "translated": False, "error_kind": classify_api_error(exc)}


# ---------------------------------------------------------------------------
# Module 4 (part 1): Daily Safety Briefing / Toolbox Talk generator
# ---------------------------------------------------------------------------

def _toolbox_talk_language_instruction(lang: str) -> str:
    """Same generic name-map approach as _language_instruction() above, just
    phrased for the toolbox-talk generator's own prompt wording."""
    name = LANGUAGE_DISPLAY_NAMES.get(lang, "French")
    instruction = f"Write the toolbox talk in {name}."
    if lang in NON_LATIN_SCRIPT_LANGS:
        instruction += " Keep technical acronyms and units in Latin script."
    return instruction


def generate_daily_briefing(site_name: str, scheduled_tasks: list[str],
                             weather_summary: dict, api_key: str | None,
                             lang: str = "fr") -> dict:
    """
    Generates a short, spoken-aloud-ready daily "toolbox talk" script,
    tailored to today's scheduled tasks and today's live weather. This is
    a genuinely different artifact from generate_narrative()'s per-
    assessment briefing: a toolbox talk is read aloud to an assembled crew
    at shift start, covering the whole day's plan, not one module's result.

    weather_summary: any dict of current conditions - typically the output
    of data_feeds.fetch_live_weather_universal() or a risk_engine result.

    Falls back to a simple templated toolbox talk (task list + a generic
    weather-awareness reminder) if no API key is supplied or the call
    fails - same offline-first guarantee as generate_narrative().

    Returns {"script": str, "source": "ai" | "template", "error_kind": str | None}.
    """
    if not api_key:
        return {"script": _fallback_toolbox_talk(site_name, scheduled_tasks, weather_summary, lang),
                "source": "template", "error_kind": "no_api_key"}

    lang_instruction = _toolbox_talk_language_instruction(lang)
    tasks_text = "\n".join(f"- {task}" for task in scheduled_tasks) or "- No tasks scheduled"

    prompt = (
        "You are drafting a morning toolbox talk (safety briefing) for a "
        "construction site foreman to read aloud to the assembled crew "
        "before shift start. Keep it under 200 words, spoken register (short "
        "sentences, no bullet-heavy jargon), and structured as: (1) today's "
        "planned tasks, (2) today's weather-driven hazard to watch for, "
        "(3) one specific reminder tied to that hazard, (4) a closing safety "
        "reminder. Do not invent a name for anyone.\n\n"
        f"{lang_instruction}\n\n"
        f"SITE: {site_name}\n"
        f"TODAY'S SCHEDULED TASKS:\n{tasks_text}\n\n"
        f"TODAY'S WEATHER/CONDITIONS DATA: {weather_summary}"
    )

    try:
        resp = requests.post(
            ANTHROPIC_URL,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={"model": MODEL, "max_tokens": 500, "messages": [{"role": "user", "content": prompt}]},
            timeout=20,
        )
        resp.raise_for_status()
        data = resp.json()
        parts = [b["text"] for b in data.get("content", []) if b.get("type") == "text"]
        script = "\n".join(parts).strip()
        if not script:
            return {"script": _fallback_toolbox_talk(site_name, scheduled_tasks, weather_summary, lang),
                    "source": "template", "error_kind": "empty_response"}
        return {"script": script, "source": "ai", "error_kind": None}
    except Exception as exc:  # noqa: BLE001
        return {"script": _fallback_toolbox_talk(site_name, scheduled_tasks, weather_summary, lang),
                "source": "template", "error_kind": classify_api_error(exc)}


_TOOLBOX_NO_TASKS_TEXT = {
    "en": "no specific tasks logged", "fr": "aucune tâche spécifique enregistrée",
    "ar": "لا توجد مهام محددة مسجلة", "es": "no hay tareas específicas registradas",
    "zh": "未记录具体任务", "ja": "特定のタスクは記録されていません",
    "hi": "कोई विशिष्ट कार्य दर्ज नहीं", "ur": "کوئی مخصوص کام درج نہیں",
    "da": "ingen specifikke opgaver registreret", "nl": "geen specifieke taken geregistreerd",
    "no": "ingen spesifikke oppgaver registrert", "sv": "inga specifika uppgifter registrerade",
    "pt": "nenhuma tarefa específica registrada", "de": "keine spezifischen Aufgaben erfasst",
}

# {site_name}/{tasks_text}/{weather_summary} placeholders.
_TOOLBOX_TALK_TEMPLATE = {
    "en": "Good morning team. Today at {site_name}, planned work includes: {tasks_text}. "
          "Current conditions: {weather_summary}. Check today's MAKU risk assessment for "
          "your work area before starting, follow the posted controls, and report any "
          "change in conditions to your supervisor immediately. Stay safe out there.",
    "fr": "Bonjour à l'équipe. Aujourd'hui sur {site_name}, les travaux prévus sont : "
          "{tasks_text}. Conditions actuelles : {weather_summary}. Consultez l'évaluation "
          "de risque MAKU pour votre zone de travail avant de commencer, respectez les "
          "mesures de contrôle affichées, et signalez immédiatement tout changement de "
          "conditions à votre superviseur.",
    "ar": "صباح الخير للفريق. اليوم في {site_name}، تشمل الأعمال المخططة: {tasks_text}. "
          "الظروف الحالية: {weather_summary}. تحقق من تقييم مخاطر MAKU لمنطقة عملك قبل "
          "البدء، واتبع إجراءات التحكم المعلنة، وأبلغ مشرفك فوراً عن أي تغيير في الظروف.",
    "es": "Buenos días equipo. Hoy en {site_name}, el trabajo planificado incluye: "
          "{tasks_text}. Condiciones actuales: {weather_summary}. Revise la evaluación de "
          "riesgo de MAKU para su área de trabajo antes de comenzar, siga los controles "
          "indicados, e informe cualquier cambio en las condiciones a su supervisor de "
          "inmediato.",
    "zh": "早上好，各位。今天在{site_name}，计划中的工作包括：{tasks_text}。当前状况："
          "{weather_summary}。开始工作前请查看今天的MAKU风险评估，遵守已公布的管控措施，"
          "并立即向主管报告任何状况变化。祝大家工作平安。",
    "ja": "チームの皆さん、おはようございます。本日{site_name}での予定作業は次のとおり"
          "です：{tasks_text}。現在の状況：{weather_summary}。作業開始前に本日のMAKU"
          "リスク評価を確認し、掲示された管理策に従い、状況に変化があれば直ちに監督者に"
          "報告してください。安全第一でお願いします。",
    "hi": "शुभ प्रभात टीम। आज {site_name} पर नियोजित कार्य में शामिल हैं: {tasks_text}। "
          "मौजूदा स्थितियां: {weather_summary}। काम शुरू करने से पहले अपने कार्य क्षेत्र "
          "के लिए आज का MAKU जोखिम आकलन देखें, बताए गए नियंत्रण उपायों का पालन करें, और "
          "स्थितियों में किसी भी बदलाव की सूचना तुरंत अपने पर्यवेक्षक को दें। सुरक्षित रहें।",
    "ur": "صبح بخیر ٹیم۔ آج {site_name} پر منصوبہ بند کام میں شامل ہے: {tasks_text}۔ موجودہ "
          "حالات: {weather_summary}۔ کام شروع کرنے سے پہلے اپنے کام کے علاقے کے لیے آج کی "
          "MAKU رسک اسیسمنٹ دیکھیں، بتائے گئے حفاظتی اقدامات پر عمل کریں، اور حالات میں "
          "کسی بھی تبدیلی کی فوری اطلاع اپنے سپروائزر کو دیں۔ محفوظ رہیں۔",
    "da": "Godmorgen, team. I dag på {site_name} omfatter det planlagte arbejde: "
          "{tasks_text}. Nuværende forhold: {weather_summary}. Tjek dagens MAKU-"
          "risikovurdering for dit arbejdsområde, før du starter, følg de angivne "
          "foranstaltninger, og rapportér straks enhver ændring i forholdene til din "
          "leder. Pas godt på jer selv derude.",
    "nl": "Goedemorgen team. Vandaag bij {site_name} omvat het geplande werk: "
          "{tasks_text}. Huidige omstandigheden: {weather_summary}. Controleer de MAKU-"
          "risicobeoordeling van vandaag voor uw werkgebied voordat u begint, volg de "
          "aangegeven beheersmaatregelen en meld elke verandering in de omstandigheden "
          "onmiddellijk aan uw leidinggevende. Blijf veilig daarbuiten.",
    "no": "God morgen, team. I dag ved {site_name} omfatter planlagt arbeid: "
          "{tasks_text}. Nåværende forhold: {weather_summary}. Sjekk dagens MAKU-"
          "risikovurdering for arbeidsområdet ditt før du starter, følg de angitte "
          "tiltakene, og meld fra om enhver endring i forholdene til lederen din "
          "umiddelbart. Vær forsiktige der ute.",
    "sv": "God morgon, team. Idag på {site_name} omfattar det planerade arbetet: "
          "{tasks_text}. Nuvarande förhållanden: {weather_summary}. Kontrollera dagens "
          "MAKU-riskbedömning för ditt arbetsområde innan ni börjar, följ de angivna "
          "åtgärderna och rapportera omedelbart eventuella förändringar i förhållandena "
          "till er arbetsledare. Var försiktiga där ute.",
    "pt": "Bom dia, equipe. Hoje em {site_name}, o trabalho planejado inclui: "
          "{tasks_text}. Condições atuais: {weather_summary}. Verifique a avaliação de "
          "risco MAKU de hoje para sua área de trabalho antes de começar, siga os "
          "controles indicados e informe qualquer mudança nas condições ao seu "
          "supervisor imediatamente. Fiquem seguros por aí.",
    "de": "Guten Morgen, Team. Heute sind bei {site_name} folgende Arbeiten geplant: "
          "{tasks_text}. Aktuelle Bedingungen: {weather_summary}. Prüfen Sie vor "
          "Arbeitsbeginn die heutige MAKU-Risikobewertung für Ihren Arbeitsbereich, "
          "befolgen Sie die angegebenen Kontrollmaßnahmen und melden Sie jede Änderung "
          "der Bedingungen sofort Ihrem Vorgesetzten. Bleiben Sie sicher da draußen.",
}


def _fallback_toolbox_talk(site_name: str, scheduled_tasks: list[str], weather_summary: dict, lang: str) -> str:
    """Offline template - no API dependency, always available."""
    tasks_text = ", ".join(scheduled_tasks) if scheduled_tasks else (
        _TOOLBOX_NO_TASKS_TEXT.get(lang, _TOOLBOX_NO_TASKS_TEXT["fr"])
    )
    template = _TOOLBOX_TALK_TEMPLATE.get(lang, _TOOLBOX_TALK_TEMPLATE["fr"])
    return template.format(site_name=site_name, tasks_text=tasks_text, weather_summary=weather_summary)


# ---------------------------------------------------------------------------
# Module 4 (part 2): Predictive forecasting layer
# ---------------------------------------------------------------------------
# Mathematical Isolation rule still applies: this NEVER computes a new risk
# number. It runs the SAME risk_engine function the module already uses,
# once per forecast point, and looks at the sequence of already-trusted
# risk_band values it returns. The only new "logic" here is "does the band
# get worse later", which is orchestration, not a risk formula.

_SEVERITY_ORDER = ["LOW", "MODERATE", "HIGH", "CRITICAL",
                   "Low", "Moderate", "High", "Extreme"]  # covers both naming conventions used across modules


def _severity_rank(band: str) -> int:
    try:
        return _SEVERITY_ORDER.index(band)
    except ValueError:
        return -1  # unknown label - treated as "can't compare", never as "safe"


def predict_forecast_breach(risk_fn, current_kwargs: dict, forecast_points: list[dict]) -> dict:
    """
    Runs risk_fn(**current_kwargs) plus risk_fn(**point) for every point in
    forecast_points (each point is a kwargs dict matching risk_fn's
    signature, plus an optional "label" key like "14:00" or "in 4h" used
    only for display - it's popped before the call). Flags the first
    forecast point where risk crosses into a worse band than the current
    reading, or into a safety-override state, whichever comes first.

    Works across every module's risk function unchanged, since it only
    reads the standard risk_band/safety_override fields every
    calculate_*_kinetic_risk() function already returns.

    Returns:
        {
          "currently_critical": bool,
          "will_breach": bool,
          "breach_label": str | None,
          "breach_band": str | None,
          "current_band": str,
        }
    """
    current_result = risk_fn(**current_kwargs)
    current_band = current_result.get("risk_band", "Unknown")
    current_rank = _severity_rank(current_band)
    currently_critical = bool(current_result.get("safety_override"))

    if currently_critical:
        return {
            "currently_critical": True, "will_breach": False,
            "breach_label": None, "breach_band": current_band, "current_band": current_band,
        }

    for point in forecast_points:
        point = dict(point)
        label = point.pop("label", None)
        forecast_result = risk_fn(**point)
        forecast_band = forecast_result.get("risk_band", "Unknown")
        forecast_rank = _severity_rank(forecast_band)
        if forecast_result.get("safety_override") or (forecast_rank > current_rank >= 0):
            return {
                "currently_critical": False, "will_breach": True,
                "breach_label": label, "breach_band": forecast_band, "current_band": current_band,
            }

    return {
        "currently_critical": False, "will_breach": False,
        "breach_label": None, "breach_band": None, "current_band": current_band,
    }


_PREDICTIVE_ALERT_TEMPLATE = {
    "en": "Proactive alert: conditions are forecast to reach {band} risk {when}. "
          "Recommended: schedule mandatory crew rotation or task adjustment before "
          "that window, rather than reacting once the threshold is already crossed.",
    "fr": "Alerte proactive : les conditions devraient atteindre un risque {band} {when}. "
          "Recommandation : planifier une rotation d'équipe ou un ajustement des tâches "
          "avant cette échéance, plutôt que de réagir une fois le seuil déjà franchi.",
    "ar": "تنبيه استباقي: من المتوقع أن تصل الظروف إلى مستوى خطورة {band} {when}. "
          "التوصية: جدولة تناوب إلزامي للطاقم أو تعديل المهام قبل ذلك الموعد، بدلاً "
          "من الاستجابة بعد تجاوز الحد بالفعل.",
    "es": "Alerta proactiva: se prevé que las condiciones alcancen un riesgo {band} {when}. "
          "Recomendación: programe una rotación obligatoria de cuadrilla o un ajuste de "
          "tareas antes de ese momento, en lugar de reaccionar una vez superado el umbral.",
    "zh": "主动预警：预计条件将在{when}达到{band}风险水平。建议：在该时段之前安排强制性"
          "人员轮换或任务调整，而不是等到阈值已被突破后才做出反应。",
    "ja": "予防的アラート：{when}に条件が{band}リスクに達すると予測されています。推奨"
          "事項：しきい値を超えてから対応するのではなく、その時間帯より前に必須の要員"
          "交代または作業内容の調整を計画してください。",
    "hi": "सक्रिय चेतावनी: पूर्वानुमान है कि स्थितियां {when} {band} जोखिम स्तर तक "
          "पहुंच जाएंगी। सिफारिश: सीमा पार होने के बाद प्रतिक्रिया देने के बजाय, उस "
          "समय से पहले अनिवार्य दल परिवर्तन या कार्य समायोजन की योजना बनाएं।",
    "ur": "فعال انتباہ: توقع ہے کہ حالات {when} {band} خطرے کی سطح تک پہنچ جائیں گے۔ "
          "سفارش: حد عبور ہونے کے بعد ردعمل دینے کے بجائے، اس وقت سے پہلے لازمی عملے "
          "کی گردش یا کام میں تبدیلی کا شیڈول بنائیں۔",
    "da": "Proaktiv advarsel: forholdene forventes at nå {band}-risiko {when}. "
          "Anbefaling: planlæg obligatorisk holdrotation eller opgavejustering inden "
          "dette tidspunkt, i stedet for at reagere efter grænsen allerede er overskredet.",
    "nl": "Proactieve waarschuwing: verwacht wordt dat de omstandigheden {when} een "
          "{band}-risico bereiken. Aanbeveling: plan een verplichte ploegenwisseling of "
          "taakaanpassing vóór dat moment, in plaats van te reageren nadat de drempel "
          "al is overschreden.",
    "no": "Proaktivt varsel: forholdene forventes å nå {band}-risiko {when}. Anbefaling: "
          "planlegg obligatorisk mannskapsrotasjon eller oppgavejustering før det "
          "tidspunktet, i stedet for å reagere etter at terskelen allerede er overskredet.",
    "sv": "Proaktiv varning: förhållandena förväntas nå {band}-risk {when}. "
          "Rekommendation: planera obligatorisk personalrotation eller uppgiftsjustering "
          "innan dess, i stället för att reagera efter att gränsvärdet redan har "
          "överskridits.",
    "pt": "Alerta proativo: prevê-se que as condições atinjam o risco {band} {when}. "
          "Recomendação: programe a rotação obrigatória da equipe ou o ajuste de "
          "tarefas antes desse momento, em vez de reagir depois que o limite já tiver "
          "sido ultrapassado.",
    "de": "Proaktive Warnung: Es wird erwartet, dass die Bedingungen {when} ein "
          "{band}-Risiko erreichen. Empfehlung: Planen Sie eine obligatorische "
          "Teamrotation oder Aufgabenanpassung vor diesem Zeitpunkt, anstatt erst zu "
          "reagieren, nachdem der Schwellenwert bereits überschritten wurde.",
}
_WHEN_FALLBACK = {
    "en": "later in this shift", "fr": "plus tard dans ce poste",
    "ar": "لاحقاً خلال هذه الوردية", "es": "más tarde en este turno",
    "zh": "本班次晚些时候", "ja": "このシフトの後半",
    "hi": "इस शिफ्ट में बाद में", "ur": "اس شفٹ میں بعد میں",
    "da": "senere i denne vagt", "nl": "later in deze dienst",
    "no": "senere i dette skiftet", "sv": "senare under detta skift",
    "pt": "mais tarde neste turno", "de": "später in dieser Schicht",
}


def generate_predictive_alert(breach_result: dict, lang: str = "fr") -> str | None:
    """
    Turns a predict_forecast_breach() result into a plain-language proactive
    alert string, or None if no breach is predicted. Purely templated (no
    API call) - the whole point of a proactive scheduling alert is that it
    must be instant and always available, never gated behind network access.
    """
    if not breach_result.get("will_breach"):
        return None
    when = breach_result.get("breach_label") or _WHEN_FALLBACK.get(lang, _WHEN_FALLBACK["fr"])
    template = _PREDICTIVE_ALERT_TEMPLATE.get(lang, _PREDICTIVE_ALERT_TEMPLATE["fr"])
    return template.format(band=breach_result["breach_band"], when=when)


# ---------------------------------------------------------------------------
# Advance Tomorrow Forecasting Layer (J+1 Shift Planning)
# ---------------------------------------------------------------------------
# Distinct from predict_forecast_breach() above (which flags a same-shift
# band-crossing using an existing risk_fn) and from generate_daily_briefing()
# (today's toolbox talk): this looks specifically at TOMORROW's forecast
# row (index 1 in a data_feeds.fetch_*_forecast()-shaped dict - index 0 is
# today per Open-Meteo's daily-forecast convention) and produces a note a
# scheduler reads the evening before, to decide whether tomorrow's shift
# plan itself needs adjusting (e.g. push morning crane lifts to the
# afternoon ahead of a forecast wind spike, or swap a heavy-exertion task
# to the cooler part of the day ahead of a forecast heat spike).

_INSUFFICIENT_FORECAST_NOTE = {
    "en": "Insufficient forecast data to build tomorrow's pre-briefing (need at least 2 "
          "days of forecast data) - proceed with today's standard shift-start assessment.",
    "fr": "Données de prévision insuffisantes pour établir le pré-briefing de demain "
          "(au moins 2 jours de prévisions sont nécessaires) - procédez à l'évaluation "
          "standard de début de poste d'aujourd'hui.",
    "ar": "بيانات التوقعات غير كافية لإعداد إحاطة الغد المسبقة (يلزم توفر بيانات توقعات "
          "ليومين على الأقل) - تابع بالتقييم القياسي لبداية الوردية اليوم.",
    "es": "Datos de pronóstico insuficientes para elaborar el pre-briefing de mañana (se "
          "necesitan al menos 2 días de datos de pronóstico) - proceda con la evaluación "
          "estándar de inicio de turno de hoy.",
    "zh": "预测数据不足，无法生成明日预先简报（至少需要2天的预测数据）——请按今天的标准班前评估继续。",
    "ja": "明日の事前ブリーフィングを作成するための予報データが不足しています（少なくとも2日分の"
          "予報データが必要です）。本日の標準的なシフト開始時評価を進めてください。",
    "hi": "कल की पूर्व-ब्रीफिंग तैयार करने के लिए पूर्वानुमान डेटा अपर्याप्त है (कम से कम 2 दिनों "
          "के पूर्वानुमान डेटा की आवश्यकता है) - आज के मानक शिफ्ट-प्रारंभ आकलन के साथ आगे बढ़ें।",
    "ur": "کل کی پیشگی بریفنگ تیار کرنے کے لیے پیشن گوئی کا ڈیٹا ناکافی ہے (کم از کم 2 دن کا "
          "ڈیٹا درکار ہے) - آج کے معیاری شفٹ کے آغاز کے جائزے کے ساتھ آگے بڑھیں۔",
    "da": "Utilstrækkelige prognosedata til at udarbejde i morgens pre-briefing (kræver "
          "mindst 2 dages prognosedata) - fortsæt med dagens standardvurdering ved "
          "vagtstart.",
    "nl": "Onvoldoende prognosegegevens om de pre-briefing van morgen op te stellen "
          "(minimaal 2 dagen prognosegegevens nodig) - ga verder met de standaard "
          "beoordeling bij aanvang van de huidige dienst.",
    "no": "Utilstrekkelige prognosedata til å lage morgendagens forhåndsbriefing (krever "
          "minst 2 dagers prognosedata) - fortsett med dagens standard vurdering ved "
          "skiftstart.",
    "sv": "Otillräckliga prognosdata för att skapa morgondagens förhandsbriefing (kräver "
          "minst 2 dagars prognosdata) - fortsätt med dagens standardbedömning vid "
          "skiftstart.",
    "pt": "Dados de previsão insuficientes para elaborar o pré-briefing de amanhã "
          "(necessários pelo menos 2 dias de dados de previsão) - prossiga com a "
          "avaliação padrão de início de turno de hoje.",
    "de": "Unzureichende Prognosedaten, um die morgige Vorab-Besprechung zu erstellen "
          "(mindestens 2 Tage Prognosedaten erforderlich) - fahren Sie mit der "
          "heutigen Standardbewertung zu Schichtbeginn fort.",
}

_NO_KEY_FORECAST_TEMPLATE = {
    "en": "Tomorrow ({date}) forecast: {summary}. No API key supplied - review this "
          "against your module's own thresholds manually before finalizing tomorrow's shift plan.",
    "fr": "Prévision de demain ({date}) : {summary}. Aucune clé API fournie - comparez "
          "ces valeurs manuellement aux seuils de votre module avant de finaliser le plan "
          "de poste de demain.",
    "ar": "توقعات الغد ({date}): {summary}. لم يتم توفير مفتاح API - راجع هذه القيم "
          "يدوياً مقابل حدود وحدتك قبل وضع خطة وردية الغد بشكل نهائي.",
    "es": "Pronóstico de mañana ({date}): {summary}. No se proporcionó una clave API - "
          "revise estos valores manualmente contra los umbrales de su módulo antes de "
          "finalizar el plan de turno de mañana.",
    "zh": "明日（{date}）预报：{summary}。未提供API密钥——在最终确定明日班次计划前，请手动对照"
          "本模块的阈值进行核对。",
    "ja": "明日（{date}）の予報：{summary}。APIキーが指定されていません。明日のシフト計画を"
          "確定する前に、このモジュールのしきい値と手動で照合してください。",
    "hi": "कल ({date}) का पूर्वानुमान: {summary}। कोई API कुंजी प्रदान नहीं की गई - कल की "
          "शिफ्ट योजना को अंतिम रूप देने से पहले इन मूल्यों की अपने मॉड्यूल की सीमाओं से "
          "मैन्युअल रूप से समीक्षा करें।",
    "ur": "کل ({date}) کی پیشن گوئی: {summary}۔ کوئی API کلید فراہم نہیں کی گئی - کل کے "
          "شفٹ پلان کو حتمی شکل دینے سے پہلے ان اقدار کا اپنے ماڈیول کی حدود سے دستی طور "
          "پر جائزہ لیں۔",
    "da": "I morgens ({date}) prognose: {summary}. Ingen API-nøgle angivet - gennemgå "
          "disse værdier manuelt mod dit moduls egne grænseværdier, før i morgens "
          "vagtplan færdiggøres.",
    "nl": "Morgen ({date}) verwachting: {summary}. Geen API-sleutel opgegeven - "
          "controleer deze waarden handmatig aan de hand van de drempelwaarden van uw "
          "module voordat u het dienstplan van morgen afrondt.",
    "no": "Morgendagens ({date}) prognose: {summary}. Ingen API-nøkkel oppgitt - "
          "gjennomgå disse verdiene manuelt mot modulens egne terskler før morgendagens "
          "skiftplan ferdigstilles.",
    "sv": "Morgondagens ({date}) prognos: {summary}. Ingen API-nyckel angiven - granska "
          "dessa värden manuellt mot din moduls egna gränsvärden innan morgondagens "
          "skiftplan färdigställs.",
    "pt": "Previsão de amanhã ({date}): {summary}. Nenhuma chave de API fornecida - "
          "revise esses valores manualmente em relação aos limites do seu módulo antes "
          "de finalizar o plano de turno de amanhã.",
    "de": "Morgige ({date}) Prognose: {summary}. Kein API-Schlüssel angegeben - "
          "überprüfen Sie diese Werte manuell anhand der Schwellenwerte Ihres Moduls, "
          "bevor Sie den morgigen Schichtplan fertigstellen.",
}

_FORECAST_FIELD_LABELS = {
    "temperature_2m_max": "max temperature (deg C)",
    "uv_index_max": "max UV index",
    "shortwave_radiation_sum": "total shortwave radiation (MJ/m2)",
    "wind_speed_10m_max_kn": "max wind speed (knots)",
}


def _extract_tomorrow_forecast_row(forecast: dict) -> dict | None:
    """Pulls out tomorrow's (index 1) values from a data_feeds.fetch_*_
    forecast()-shaped dict. Returns None if there's no tomorrow row at all
    (never fabricates a forecast that wasn't actually returned)."""
    dates = forecast.get("dates") or []
    if len(dates) < 2:
        return None
    row = {"date": dates[1]}
    for key, values in forecast.items():
        if key in ("dates", "source") or not isinstance(values, list):
            continue
        if len(values) > 1:
            row[key] = values[1]
    return row


def generate_tomorrow_preshift_briefing(
    site_name: str,
    module: str,
    forecast: dict,
    api_key: str | None,
    lang: str = "fr",
) -> dict:
    """
    J+1 shift-planning layer: ingests tomorrow's forecast row (from a
    data_feeds.fetch_solar_forecast()/fetch_offshore_forecast()-shaped
    dict) and produces "Tomorrow's Crew Pre-Briefing Note" - actionable
    guidance for the scheduler on specific work-window adjustments (e.g.
    suspending morning crane lifts ahead of an expected wind spike, or
    moving heavy-exertion tasks to a cooler window ahead of an expected
    heat spike), read the evening before rather than reacted to the next
    morning.

    Falls back to a templated note (raw tomorrow's forecast values, no
    AI-generated tactical advice) if no API key is supplied, the call
    fails, or fewer than 2 days of forecast data are available - never
    fabricates a forecast value that wasn't actually returned by
    data_feeds.py.

    Returns {"note": str, "source": "ai" | "template" | "insufficient_data",
    "tomorrow_date": str | None, "error_kind": str | None}.
    """
    tomorrow = _extract_tomorrow_forecast_row(forecast)
    if tomorrow is None:
        return {
            "note": _INSUFFICIENT_FORECAST_NOTE.get(lang, _INSUFFICIENT_FORECAST_NOTE["fr"]),
            "source": "insufficient_data", "tomorrow_date": None, "error_kind": None,
        }

    summary_parts = [f"{_FORECAST_FIELD_LABELS.get(k, k)}: {v}" for k, v in tomorrow.items() if k != "date"]
    summary_text = "; ".join(summary_parts) or "no forecast fields available"

    if not api_key:
        return {
            "note": _NO_KEY_FORECAST_TEMPLATE.get(lang, _NO_KEY_FORECAST_TEMPLATE["fr"]).format(
                date=tomorrow["date"], summary=summary_text
            ),
            "source": "template", "tomorrow_date": tomorrow["date"], "error_kind": None,
        }

    lang_instruction = _language_instruction(lang)
    prompt = (
        "You are an HSE scheduling assistant. Given tomorrow's forecast for a "
        "construction site, write a short 'Tomorrow's Crew Pre-Briefing Note' "
        "(under 150 words) for the scheduler to read tonight, BEFORE tomorrow's "
        "shift is planned. Recommend SPECIFIC work-window adjustments if the "
        "forecast warrants them (e.g. 'suspend morning crane lifts before 10:00, "
        "expected wind spike', 'move heavy-exertion tasks to before 11:00 ahead "
        "of forecast peak heat'). If tomorrow's forecast is unremarkable for this "
        "module, say so briefly rather than inventing a concern. Do not invent "
        "a name for anyone.\n\n"
        f"{lang_instruction}\n\n"
        f"SITE: {site_name}\nMODULE: {module}\n"
        f"TOMORROW'S DATE: {tomorrow['date']}\nTOMORROW'S FORECAST: {summary_text}"
    )

    try:
        resp = requests.post(
            ANTHROPIC_URL,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={"model": MODEL, "max_tokens": 400, "messages": [{"role": "user", "content": prompt}]},
            timeout=20,
        )
        resp.raise_for_status()
        data = resp.json()
        parts = [b["text"] for b in data.get("content", []) if b.get("type") == "text"]
        note = "\n".join(parts).strip()
        if not note:
            raise ValueError("empty response")
        return {"note": note, "source": "ai", "tomorrow_date": tomorrow["date"], "error_kind": None}
    except Exception as exc:  # noqa: BLE001
        return {
            "note": _NO_KEY_FORECAST_TEMPLATE.get(lang, _NO_KEY_FORECAST_TEMPLATE["fr"]).format(
                date=tomorrow["date"], summary=summary_text
            ),
            "source": "template", "tomorrow_date": tomorrow["date"], "error_kind": classify_api_error(exc),
        }
