"""
MAKU AI Advisor Layer
=====================
Takes the transparent risk_engine.py outputs and produces:
  1. A rule-based hierarchy-of-controls recommendation (always works, no API needed)
  2. An optional plain-language narrative generated by the Anthropic API,
     if the user supplies an API key. This keeps the app fully functional
     offline/without a key, while demonstrating a genuine "AI reasoning"
     layer when a key is present - useful for the capstone demo.

Safety culture principle (informs the narrative below): compliance is the
OUTPUT of an authentic safety culture, not administrative theater - a
control list checked off on paper means nothing if it wasn't actually
implemented on site. The real test of that culture is what leadership
chooses in the moment a genuine risk-vs-cost tradeoff appears: whether they
control the risk, or cut the cost. Every AI briefing this module generates
is written to reflect that distinction, not just to restate the numbers.
"""

import os
import requests

ANTHROPIC_URL = "https://api.anthropic.com/v1/messages"
MODEL = "claude-sonnet-4-5"  # update to current model string as needed


# ---------------------------------------------------------------------------
# Rule-based hierarchy of controls (always available, no API dependency)
# ---------------------------------------------------------------------------

def solar_controls(result: dict) -> list:
    band = result["risk_band"]
    controls = []
    if band in ("Moderate", "High", "Extreme"):
        controls += [
            "Shift high-exertion tracker/module installation to early morning or late afternoon windows",
            "Enforce ACGIH work/rest cycle per calculated action level; increase rest ratio if margin exceeded",
            "Mandatory shaded rest areas / cooling stations within 100m of active work fronts",
            "Buddy system + heat-illness spotters; mandatory electrolyte replacement schedule",
        ]
    if band in ("High", "Extreme"):
        controls += [
            "Escalate to HSE manager: consider suspending non-critical outdoor MEP tasks during peak GHI hours",
            "Reflective/ventilated PPE for crews working adjacent to panel rows (elevated radiant load)",
        ]
    if not controls:
        controls = ["Maintain standard heat-safety protocol; monitor GHI/temp trend for escalation"]
    return controls


def offshore_controls(result: dict) -> list:
    controls = []
    band = result["risk_band"]
    if band in ("Moderate", "High", "Extreme"):
        controls += [
            "Adjust welding/pipe-fitting shift rotations per Humidex band; shorten exposure intervals",
            "Increase hydration monitoring; enclosed-space heat retention areas need forced ventilation checks",
        ]
    if result["wind_risk_status"] != "Normal Operations":
        controls.append(f"Wind risk status: {result['wind_risk_status']}")
    if result["safety_override"]:
        controls.insert(0, "SAFETY OVERRIDE: suspend crane/lifting and welding ops until conditions recheck")
    if not controls:
        controls = ["Maintain standard marine HSE protocol; monitor wind/humidex trend"]
    return controls


def underground_controls(result: dict) -> list:
    controls = []
    band = result["risk_band"]
    if result["safety_override"]:
        controls.append("SAFETY OVERRIDE: halt non-essential high-voltage MEP cabling work until conditions recheck")
    if result["gas_exceeds"]:
        controls.append("CO OEL exceeded - evacuate face area, verify forced ventilation, re-test before re-entry")
    if result["dust_exceeds"]:
        controls.append("PM2.5 OEL exceeded - mandatory respiratory PPE upgrade, water suppression, re-test")
    if band in ("MODERATE", "HIGH", "CRITICAL"):
        controls.append("Reduce work/rest ratio for MEP electrical crews; rotate more frequently as heat trend rises")
    if band in ("HIGH", "CRITICAL"):
        controls.append("Prioritize temporary ventilation deployment ahead of permanent system commissioning")
    if not controls:
        controls = ["Maintain standard underground HSE protocol; continue OEL and heat monitoring cadence"]
    return controls


def high_rise_controls(result: dict) -> list:
    controls = []
    band = result["risk_band"]
    if result["safety_override"]:
        controls.append(
            "SAFETY OVERRIDE: suspend all crane lifts and external-wall/curtain-wall installation "
            "until scaled wind drops below the 30-knot threshold"
        )
    if band in ("HIGH", "CRITICAL"):
        controls += [
            "Notify tower crane operator and site HSE manager of current floor-level scaled wind readings",
            "Recheck tie-off points and suspended-access rigging before resuming work at height",
        ]
    if band == "MODERATE":
        controls.append("Delay non-critical curtain-wall/riser lifts to the next confirmed calm window")
    if not controls:
        controls = ["Maintain standard at-height wind-monitoring protocol; recheck anemometer feed each shift"]
    return controls


def data_center_controls(result: dict) -> list:
    controls = []
    if result["arc_flash_danger"]:
        controls.append(
            "DANGER: arc-flash incident energy exceeds max PPE rating at this load - "
            "de-energize equipment before any work; no PPE category permits live work"
        )
    if result["confined_armed_danger"]:
        controls.append(
            "Confined ceiling-void space + armed clean-agent suppression: disarm/isolate "
            "the system and atmosphere-test (O2/asphyxiant risk) before entry"
        )
    if result["thermal_differential"] >= 15.0:
        controls.append(
            "Hot/cold-aisle thermal differential elevated - rotate commissioning crews "
            "more frequently, hydrate, reduce continuous hot-aisle dwell time"
        )
    if result["safety_override"]:
        controls.insert(0, "SAFETY OVERRIDE: halt non-essential commissioning work in this zone until conditions are rechecked")
    if not controls:
        controls = ["Maintain standard data-center commissioning HSE protocol; continue thermal, arc-flash, and confined-space monitoring cadence"]
    return controls


CONTROLS_MAP = {
    "Solar (Desert)": solar_controls,
    "Offshore (Marine)": offshore_controls,
    "Underground (Tunnel/Metro)": underground_controls,
    "High-Rise (Vertical Urban)": high_rise_controls,
    "Data Center (Controlled Critical Environment)": data_center_controls,
}


def get_controls(result: dict) -> list:
    return CONTROLS_MAP[result["module"]](result)


# ---------------------------------------------------------------------------
# Optional LLM narrative layer (Anthropic API)
# ---------------------------------------------------------------------------

def generate_narrative(result: dict, controls: list, api_key: str, lang: str = "fr") -> str:
    """
    Calls the Anthropic API to turn the structured risk_engine output into a
    short HSE-manager-facing narrative. Falls back gracefully if no key is
    provided or the call fails - the app must never depend on this to function.

    lang: UI language code ("fr" default, or "en"). Per project guidelines the
    app defaults to French, so the AI briefing is requested in French unless
    the user has switched to English. The underlying data/controls stay in
    English (they come straight from the transparent risk_engine/ai_advisor
    logic) - only the generated narrative text is localized.
    """
    if not api_key:
        return _fallback_narrative(result, controls, lang)

    language_instruction = {
        "fr": "Write your response in French.",
        "en": "Write your response in English.",
    }.get(lang, "Write your response in French.")

    prompt = (
        "You are an HSE risk communication assistant grounded in an authentic "
        "safety-culture philosophy: compliance is the OUTPUT of a genuine safety "
        "culture, not administrative theater, and the real test of that culture "
        "is whether leadership chooses to control the risk or cut the cost when "
        "the two are in tension. Given this structured construction risk "
        "assessment output (JSON-like), write a concise 3-4 sentence briefing "
        "for an HSE manager: state the risk level, the primary hazard, and the "
        "single most urgent action - framed as a real operational decision "
        "leadership needs to make now, not a checkbox to file. Be direct, "
        f"professional, no fluff. {language_instruction}\n\n"
        f"DATA: {result}\n\nRECOMMENDED CONTROLS: {controls}"
    )

    try:
        resp = requests.post(
            ANTHROPIC_URL,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": MODEL,
                "max_tokens": 300,
                "messages": [{"role": "user", "content": prompt}],
            },
            timeout=20,
        )
        resp.raise_for_status()
        data = resp.json()
        text_parts = [b["text"] for b in data.get("content", []) if b.get("type") == "text"]
        return "\n".join(text_parts).strip() or _fallback_narrative(result, controls, lang)
    except Exception as e:
        return _fallback_narrative(result, controls, lang) + f"\n\n[AI narrative unavailable: {e}]"


def _fallback_narrative(result: dict, controls: list, lang: str = "fr") -> str:
    """
    Offline/no-key fallback narrative. Localized for fr/en since it's the
    only user-facing text ai_advisor produces without the API; the
    underlying risk_band/primary_hazard/controls values themselves stay in
    English (they're the transparent engine's raw vocabulary).

    For elevated risk bands, appends a short line reflecting the safety
    culture principle above: this is the moment where leadership either
    controls the risk or cuts the cost, and that choice - not the paperwork -
    is what the AI briefing is here to surface.
    """
    band = result.get("risk_band", "Unknown")
    hazard = result.get("primary_hazard", "")
    default_control = "Maintain standard protocol" if lang == "en" else "Maintenir le protocole standard"
    top_control = controls[0] if controls else default_control

    elevated = str(band).upper() in ("HIGH", "EXTREME", "CRITICAL", "EXTREME (DANGER)")

    if lang == "en":
        text = (
            f"Risk level: {band}. Primary hazard: {hazard}. "
            f"Most urgent action: {top_control}."
        )
        if elevated:
            text += (
                " This is a leadership decision, not a paperwork exercise: "
                "controlling this risk now is what an authentic safety culture "
                "looks like in practice."
            )
        return text

    text = (
        f"Niveau de risque : {band}. Danger principal : {hazard}. "
        f"Action la plus urgente : {top_control}."
    )
    if elevated:
        text += (
            " Ceci est une décision de leadership, pas un exercice administratif : "
            "contrôler ce risque maintenant, c'est ce à quoi ressemble une culture "
            "de sécurité authentique dans la pratique."
        )
    return text
